{{- if eq .Values.controller "nginx" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "ingress.apiService" . }}
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ingress.frontendService" . }}
                port:
                  number: 80
{{- end }}