apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-secret
type: Opaque
stringData:
  user:     {{ .Values.global.dbUser | quote }}
  password: {{ .Values.global.dbPassword | quote }}
  dbname:   {{ .Values.global.dbName | quote }}