replicaCount: 1

image:
  repository: ghcr.io/florisdelahaye/m5-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

modelDir: /models

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}