apiVersion: v2
name: m5-forecast
description: M5 What-If Profit Simulator
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: api
    version: "0.1.0"
    repository: "file://charts/api"
  - name: frontend
    version: "0.1.0"
    repository: "file://charts/frontend"
  - name: database
    version: "0.1.0"
    repository: "file://charts/database"
  - name: ingress
    version: "0.1.0"
    repository: "file://charts/ingress"