api:
  image:
    repository: ghcr.io/rune-mortier/m5-api
    tag: latest
    pullPolicy: Always

frontend:
  image:
    repository: ghcr.io/rune-mortier/m5-frontend
    tag: latest
    pullPolicy: Always